### ISSUE TITLE
Not possible to download VNF Packages

### ISSUE THREAD

**Issue by rafael-direito** [openslice/io.openslice.portal.api#14]
When listing all VNFs, one is presented with a button to download a VNF Package. See image below:

![Screenshot 2023-09-25 at 15 45 48](https://github.com/openslice/io.openslice.portal.api/assets/30239227/d4c9af74-0395-46de-a1c3-efcf4e3ff953)

When clicking on that button, Openslice redirects the user to a new webpage, through which the package should be immediately downloaded. However, the base path of that path is not the one of Openslice's Portal, but rather _portal.example.org_. See image below:

![Screenshot 2023-09-25 at 15 45 57](https://github.com/openslice/io.openslice.portal.api/assets/30239227/1c2df911-86e8-497a-bff1-82ffde69ba3d)

Such issue is originated by the implementation of the [PortalPropertiesService.java class ](https://github.com/openslice/io.openslice.portal.api/blob/acd3f8530e802b1d367bd358c318fac7434b9f55/src/main/java/portal/api/service/PortalPropertiesService.java#L90), where the `maindomain` is always _portal.example.org_. Thus, to fix this issue, one should pass this variable in the docker-compose / k8s manifests, which allows this value to be customized by the Openslice providers.

**Comment by ctranoris** [comment]
hi @rafael-direito I'm adding also @Ioannischatzis @kostistr . Perhaps another quick fix is in html javascript code to remove the domain and point just to path. Then the browser will take care for the correct url. I'm not sure

**Comment by rafael-direito** [comment]
Hey @ctranoris 
We know what the issue is and how to fix it. Actually, I'm doing it right now... :)
Thus, I dont think @Ioannischatzis  and @kostistr  should be needed to solve this, but I leave it up to you :)

**Comment by rafael-direito** [comment]
Since there are several variables in [PortalPropertiesService.java class](https://github.com/openslice/io.openslice.portal.api/blob/acd3f8530e802b1d367bd358c318fac7434b9f55/src/main/java/portal/api/service/PortalPropertiesService.java#L90), perhaps it would be better to consume them from the application's properties. What do you say? @ctranoris

**Comment by ctranoris** [comment]
I was just thinking that an html fix might be easier and affects probably only one file, but I'm not sure for this. What are you saying is also correct, but (probably) we just need also to change later the docker compose. In any case is ok. Let's fix it :-)

**Comment by ctranoris** [comment]
Hi Rafael, it's ok to keep it like this. I see also some parameters like jenkins CI etc. We don't know how they are used, but for this commit let's keep it. It is better if in future commits we can keep the scope of the commit for a single issue . (e.g. the jenkins parameters could be another commit for another issue)
